default: &default

  adapter: postgresql
  encoding: unicode
  pool: 5


development:
  <<: *default
  database: mix_master_development

test:
  <<: *default
  database: mix_master_test

production:
  <<: *default
  database: mix_master_production
  password: <%= ENV['MIX_MASTER_DATABASE_PASSWORD'] %>
